apiVersion: apps/v1
kind: Deployment
metadata:
  name: conversao-temperatura
spec:
  replicas: 10
  selector:
    matchLabels:
      app: conversao-temperatura
  template:
    metadata:
      labels:
        app: conversao-temperatura
    spec:
      containers:
        - name: conversao-temperatura
          image: oriovaldof/conversao-temperatura:v2
---
apiVersion: v1
kind: Service
metadata:
  name: conversaotemperatura
spec:
  selector:
    app: conversao-temperatura
  ports:
  - port: 80
    targetPort: 8080
    nodePort: 30000
  type: NodePort